spring.datasource.url=${DB_URL:jdbc:mysql://gondola.proxy.rlwy.net:52337/coogpath}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:pwCbaynVjzgPErYfhRCHcteChDLHNYrr}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.flyway.baseline-version=${FLYWAY_BASELINE_VERSION:4}
